"""Adding picture field to user

Revision ID: 11317cfeb97d
Revises: d8027bc9b6eb
Create Date: 2024-11-30 11:07:46.025477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11317cfeb97d'
down_revision = 'd8027bc9b6eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('picture')

    # ### end Alembic commands ###
