"""empty message

Revision ID: 9ad9cbea0620
Revises: 9dbc623ed595
Create Date: 2024-12-02 12:43:21.745943

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9ad9cbea0620'
down_revision = '9dbc623ed595'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('website', sa.String(length=140), nullable=True),
    sa.Column('picture', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_watch_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('netflix_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['netflix_id'], ['netflix.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('netflix', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('director',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('cast',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('country',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('release_year',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('listed_in',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('netflix', schema=None) as batch_op:
        batch_op.alter_column('listed_in',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('release_year',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('country',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('cast',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('director',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('type',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)

    op.drop_table('user_watch_preferences')
    op.drop_table('post')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
