"""empty message

Revision ID: 9dcd6c03cbc9
Revises: 6a91c24e37e5
Create Date: 2024-12-02 12:26:51.514696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dcd6c03cbc9'
down_revision = '6a91c24e37e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_watch_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('netflix_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['netflix_id'], ['netflix.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('_netflix_old_20241202')
    with op.batch_alter_table('netflix', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('netflix', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=False,
               autoincrement=True)

    op.create_table('_netflix_old_20241202',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('title', sa.VARCHAR(length=20), nullable=True),
    sa.Column('director', sa.VARCHAR(length=20), nullable=True),
    sa.Column('cast', sa.VARCHAR(length=20), nullable=True),
    sa.Column('country', sa.VARCHAR(length=20), nullable=True),
    sa.Column('date_added', sa.DATETIME(), nullable=True),
    sa.Column('release_year', sa.VARCHAR(length=20), nullable=True),
    sa.Column('rating', sa.INTEGER(), nullable=True),
    sa.Column('duration', sa.INTEGER(), nullable=True),
    sa.Column('listed_in', sa.VARCHAR(length=20), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_watch_preferences')
    # ### end Alembic commands ###
